version: '3.9'

services:
  # back-api:
  #   build: .
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - database
  #   command: sh -c "npm run build-api"
  
  
  # back-products:
  #   build: .
  #   depends_on:
  #     - back-api
  #   ports:
  #     - "3003:3003"
  #   command: sh -c "npm run build-products"

  # back-db:
  #   build: .
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     - DATABASE_PUBLIC_URL=database
  #   links:
  #     - database
  #   networks:
  #     - backend
  #   command: sh -c "npm run build-db"
  
  database:
    image: mysql:8
    restart: always
    ports:
      - "33006:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=339P&VnK^BiuYqTIsOGJd
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:

networks:
  backend:
    driver: bridge